baseurl="https://allanchristiancarlos.github.io/"
languageCode="en-us"
title="Allan Christian Carlos (2021) | Software Engineer"
theme="hugo-theme-hello-friend-ng"
paginate=2
Copyright="©allanchristiancarlos 2021"
canonifyurls=true
publishDir="docs"